In [2]:
import numpy as np

### Транспонирование матрицы

In [6]:
A = np.random.randint(-20,25,(3,4))
print(A)

[[ 10 -16  17   1]
 [  1   0   8   0]
 [ 18  10  19  22]]


In [7]:
A_T = A.T
print("Транспонированная матрица:\n",A_T)

Транспонированная матрица:
 [[ 10   1  18]
 [-16   0  10]
 [ 17   8  19]
 [  1   0  22]]


#### Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [8]:
A = np.random.randint(-20,25,(3,4))
print(A)
print((A.T).T)

[[ -2   9  -2   6]
 [  2  10   5 -12]
 [ 13 -13  11   2]]
[[ -2   9  -2   6]
 [  2  10   5 -12]
 [ 13 -13  11   2]]


#### Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [12]:
A = np.random.randint(-10,10,(3,4))
B = np.random.randint(0,25,(3,4))
L = (A+B).T
R = A.T + B.T
print("Транспонирование суммы:\n",L)
print("Сумма транспонированных матриц:\n",R)

Транспонирование суммы:
 [[24 10  7]
 [ 4 -7 -3]
 [ 3  7 17]
 [23 11 26]]
Сумма транспонированных матриц:
 [[24 10  7]
 [ 4 -7 -3]
 [ 3  7 17]
 [23 11 26]]


#### Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке

In [13]:
A = np.random.randint(-10,30,(3,4))
B = np.random.randint(0,25,(4,3))
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print("Транспонирование произведения матриц:\n",L)
print("Произведение транспонированных матриц расставленных в обратном порядке:\n",R)

Транспонирование произведения матриц:
 [[ 201  299   -7]
 [1224  869  680]
 [ 963  516  535]]
Произведение транспонированных матриц расставленных в обратном порядке:
 [[ 201  299   -7]
 [1224  869  680]
 [ 963  516  535]]


#### Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [14]:
A = np.random.randint(0,25,(4,4))
k = 5
L = (k * A).T
R = k * A.T
print("Транспонирование произведения матрицы на число:\n",L)
print("Произведение этого числа на транспонированную матрицу:\n",R)

Транспонирование произведения матрицы на число:
 [[ 20  80  45  25]
 [105  60  40  55]
 [ 15   0 110 100]
 [ 40  95  70  90]]
Произведение этого числа на транспонированную матрицу:
 [[ 20  80  45  25]
 [105  60  40  55]
 [ 15   0 110 100]
 [ 40  95  70  90]]


#### Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [18]:
A = np.random.randint(0,10,(4,4))
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print("Определитель исходной матрицы:",format(A_det, '.9g'))
print("Определитель транспонированной матрицы:",format(A_T_det, '.9g'))

Определитель исходной матрицы: -2
Определитель транспонированной матрицы: -2


### Действия над матрицами

#### Умножение матрицы на число

In [19]:
A = np.random.randint(-10,10,(4,4))
print(A)
print("Произведение матрицы на число:\n",A * 4)

[[ -5 -10   3  -5]
 [  1   7   1  -2]
 [  6  -2   1  -7]
 [  0   1   1  -3]]
Произведение матрицы на число:
 [[-20 -40  12 -20]
 [  4  28   4  -8]
 [ 24  -8   4 -28]
 [  0   4   4 -12]]


#### Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице

In [22]:
A = np.random.randint(-10,10,(4,4))
print("Исходная матрица:\n",A)
print("Матрица умноженная на единицу:\n",A * 1)

Исходная матрица:
 [[ -7   2  -1 -10]
 [ -3  -5   8  -2]
 [  2  -2  -4   1]
 [ -7   0   7  -4]]
Матрица умноженная на единицу:
 [[ -7   2  -1 -10]
 [ -3  -5   8  -2]
 [  2  -2  -4   1]
 [ -7   0   7  -4]]


#### Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы

In [23]:
A = np.random.randint(-10,10,(4,4))
print("Исходная матрица:\n",A)
print("Произведение матрицы на ноль:\n",A * 0)

Исходная матрица:
 [[ 9 -9  3  0]
 [-1  3 -9 -4]
 [ 6 -9  7  6]
 [-5 -2  4 -6]]
Произведение матрицы на ноль:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел

In [25]:
A = np.random.randint(-10,10,(4,4))
print("Исходная матрица:\n",A)
d = 5
c = 4
L = (d + c) * A
R = d * A + c * A
print("Произведение матрицы на сумму чисел:\n", L)
print("Сумма произведений матрицы на каждое из этих чисел:\n", R)

Исходная матрица:
 [[  5   1   8  -1]
 [  0   6  -9 -10]
 [  6   9  -8   8]
 [  7  -3   2  -1]]
Произведение матрицы на сумму чисел:
 [[ 45   9  72  -9]
 [  0  54 -81 -90]
 [ 54  81 -72  72]
 [ 63 -27  18  -9]]
Сумма произведений матрицы на каждое из этих чисел:
 [[ 45   9  72  -9]
 [  0  54 -81 -90]
 [ 54  81 -72  72]
 [ 63 -27  18  -9]]


#### Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [27]:
A = np.random.randint(-10,10,(4,4))
print("Исходная матрица:\n",A)
d = 5
c = 4
L = (d * c) * A
R = d * (c * A)
print("Произведение матрицы на произведение двух чисел:\n", L)
print("Произведение второго числа и заданной матрицы, умноженному на первое число \n", R)

Исходная матрица:
 [[  0   1   0  -1]
 [-10   4  -3   6]
 [-10 -10   7   6]
 [ -2  -2   5 -10]]
Произведение матрицы на произведение двух чисел:
 [[   0   20    0  -20]
 [-200   80  -60  120]
 [-200 -200  140  120]
 [ -40  -40  100 -200]]
Произведение второго числа и заданной матрицы, умноженному на первое число 
 [[   0   20    0  -20]
 [-200   80  -60  120]
 [-200 -200  140  120]
 [ -40  -40  100 -200]]


#### Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [30]:
A = np.random.randint(-10,10,(3,4))
print("Исходная матрица A:\n",A)
B = np.random.randint(-10,10,(3,4))
print("Исходная матрица B:\n",B)
k = 100
L = k * (A + B)
R = k * A + k * B
print("Произведение суммы матриц на число:\n", L)
print("Сумма произведений этих матриц на заданное число:\n", R)

Исходная матрица A:
 [[ 6 -7  0  0]
 [-8 -5  2  7]
 [ 2  0  3  0]]
Исходная матрица B:
 [[-10   4  -1  -1]
 [ -9   3  -4   3]
 [  4  -4  -9 -10]]
Произведение суммы матриц на число:
 [[ -400  -300  -100  -100]
 [-1700  -200  -200  1000]
 [  600  -400  -600 -1000]]
Сумма произведений этих матриц на заданное число:
 [[ -400  -300  -100  -100]
 [-1700  -200  -200  1000]
 [  600  -400  -600 -1000]]


### Cложение матрицы

#### Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [35]:
A = np.random.randint(-10,10,(3,4))
print("Исходная матрица A:\n",A)
B = np.random.randint(-10,10,(3,4))
print("Исходная матрица B:\n",B)
L = A + B
R = B + A
print("Сумма А + В:\n", L)
print("Сумма В + А:\n", R)

Исходная матрица A:
 [[ 0  2 -5  0]
 [ 6  8 -5  7]
 [-7  2  5 -9]]
Исходная матрица B:
 [[ 8 -1  4  2]
 [-2 -7 -1  2]
 [ 6  7 -4  1]]
Сумма А + В:
 [[ 8  1 -1  2]
 [ 4  1 -6  9]
 [-1  9  1 -8]]
Сумма В + А:
 [[ 8  1 -1  2]
 [ 4  1 -6  9]
 [-1  9  1 -8]]


#### Свойство 2. Ассоциативность сложения.
Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться

In [36]:
A = np.matrix('-2 -3  6; -12 -11   2 ;1 2 1')
B = np.matrix('-1  -7  -4; 10 7 9; -3   1 -10')
C = np.matrix('-7  -4  -5; 15 9 3; -11   2   8')
L = A + (B + C)
R = (A + B) + C
print("Сумма A + (B + C):\n", L)
print("Сумма (A + B) + C:\n", R)

Сумма A + (B + C):
 [[-10 -14  -3]
 [ 13   5  14]
 [-13   5  -1]]
Сумма (A + B) + C:
 [[-10 -14  -3]
 [ 13   5  14]
 [-13   5  -1]]


#### Свойство 3. Для любой матрицы существует противоположная ей, такая, что их сумма является нулевой матрицей :

In [65]:
A = np.matrix('-2 -3  6; 0 -11   2 ;1 2 1')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print("Сумма исходной и противоположной ей матриц:\n", L)
print("Нулевая матрица:\n",Z)

Сумма исходной и противоположной ей матриц:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Нулевая матрица:
 [[0 0]
 [0 0]]


#### Умножение матриц

In [38]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
C = A.dot(B)
print(C)

[[ 39 -33   4]
 [ -8  -6  22]
 [ 18 -43 -26]]


#### Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция

In [39]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
С = np.random.randint(-10,10,(3,3))
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print("Произведение A * (B * C):\n", L)
print("Произведение (A * B) * C:\n", R)

Произведение A * (B * C):
 [[ 480  -94  576]
 [1435 -822 1538]
 [1514 -554 1490]]
Произведение (A * B) * C:
 [[ 480  -94  576]
 [1435 -822 1538]
 [1514 -554 1490]]


#### Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц

In [40]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
С = np.random.randint(-10,10,(3,3))
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print("Произведение A * (B + C):\n", L)
print("Произведение A * B + A * C:\n", R)

Произведение A * (B + C):
 [[-112  176  -22]
 [ -16  119  -31]
 [-152   95  126]]
Произведение A * B + A * C:
 [[-112  176  -22]
 [ -16  119  -31]
 [-152   95  126]]


#### Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей

In [41]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
L = A.dot(B)
R = B.dot(A)
print("Произведение A * B:\n", L)
print("Произведение B * A:\n", R)

Произведение A * B:
 [[ 39 -36  30]
 [ 17  16  18]
 [ 14  22  24]]
Произведение B * A:
 [[-16  32   8]
 [-32  50   6]
 [-11  17  45]]


#### Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице

In [42]:
A = np.matrix('5 4; 4 7')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print("Произведение заданной матрицы на единичную:\n", L)
print("Произведение единичной матрицы на заданную:\n", R)
print("Исходная матрица:\n", A)

Произведение заданной матрицы на единичную:
 [[5 4]
 [4 7]]
Произведение единичной матрицы на заданную:
 [[5 4]
 [4 7]]
Исходная матрица:
 [[5 4]
 [4 7]]


#### Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице

In [43]:
A = np.matrix('5 4; 4 7')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print("Произведение заданной матрицы на нулевую:\n", L)
print("Произведение нулевой матрицы на заданную:\n", R)
print("Исходная матрица:\n", Z)

Произведение заданной матрицы на нулевую:
 [[0 0]
 [0 0]]
Произведение нулевой матрицы на заданную:
 [[0 0]
 [0 0]]
Исходная матрица:
 [[0 0]
 [0 0]]


### Определитель матрицы

In [44]:
A = np.random.randint(1,5,(3,3))
print(A)

[[3 3 3]
 [4 1 1]
 [2 2 4]]


In [45]:
np.linalg.det(A)

-17.999999999999996

#### Свойства определителя матрицы.


#### Свойство 1. Определитель матрицы остается неизменным при ее транспонировании

In [46]:
A = np.random.randint(1,5,(3,3))
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print("Опеределитель матрицы:",det_A)
print("Определитель транспонированной матрицы:",det_A_t)

[[1 4 4]
 [2 3 4]
 [3 3 1]]
[[1 2 3]
 [4 3 3]
 [4 4 1]]
Опеределитель матрицы: 19.0
Определитель транспонированной матрицы: 19.0


#### Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю

In [47]:
A = np.matrix('0 41 2; 0 5 9; 0 88 21')
print(A)
print("Опеределитель матрицы:", np.linalg.det(A))

[[ 0 41  2]
 [ 0  5  9]
 [ 0 88 21]]
Опеределитель матрицы: 0.0


#### Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный

In [48]:
A = np.matrix('0 41 2; 10 5 9; 0 88 21')
print(A)
print("Определитель матрицы А:",round(np.linalg.det(A), 3))
B = np.matrix('10 5 9; 0 41 2; 0 88 21')
print(B)
print("Определитель матрицы В:",round(np.linalg.det(B), 3))

[[ 0 41  2]
 [10  5  9]
 [ 0 88 21]]
Определитель матрицы А: -6850.0
[[10  5  9]
 [ 0 41  2]
 [ 0 88 21]]
Определитель матрицы В: 6850.0


#### Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю

In [49]:
A = np.matrix('0 41 2; 0 41 2; 16 88 21')
print(A)
print("Определитель матрицы А:",np.linalg.det(A))

[[ 0 41  2]
 [ 0 41  2]
 [16 88 21]]
Определитель матрицы А: 0.0


#### Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число

In [50]:
A = np.random.randint(1,5,(3,3))
print(A)
k = 10
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print("Опеределитель матрицы:",det_A * k)
print("Определитель матрицы умноженной на число:",det_B)

[[1 3 2]
 [4 4 1]
 [2 2 3]]
[[ 1  3  2]
 [ 4  4  1]
 [20 20 30]]
Опеределитель матрицы: -200.0
Определитель матрицы умноженной на число: -200.0


#### Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц

In [51]:
A = np.matrix('1 2 3; -1 31 4; 4 5 6')
B = np.matrix('1 2 3; 9 8 7; 4 5 6')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
R = round(np.linalg.det(C), 3)
L = round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)
print("Определитель матрицы C:", R)
print("Определитель суммы двух матриц:", L)

[[ 1  2  3]
 [ 8 39 11]
 [ 4  5  6]]
[[ 1  2  3]
 [-1 31  4]
 [ 4  5  6]]
[[1 2 3]
 [9 8 7]
 [4 5 6]]
Определитель матрицы C: -177.0
Определитель суммы двух матриц: -177.0


#### Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится

In [52]:
A = np.random.randint(1,5,(3,3))
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
R = round(np.linalg.det(A), 3)
L = round(np.linalg.det(B), 3)
print("Определитель матрицы A:", R)
print("Определитель матрицы B:", L)

[[4 1 3]
 [1 3 4]
 [3 2 3]]
[[ 4  1  3]
 [ 9  5 10]
 [ 3  2  3]]
Определитель матрицы A: -8.0
Определитель матрицы B: -8.0


#### Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю

In [53]:
A = np.random.randint(1,5,(3,3))
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
print(A)
K = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", K)

[[4 2 3]
 [1 4 1]
 [3 1 2]]
[[ 4  2  3]
 [10  4  7]
 [ 3  1  2]]
Определитель матрицы A: 0.0


#### Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю

In [54]:
A = np.random.randint(1,5,(3,3))
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
K = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", K)

[[2 3 3]
 [4 3 4]
 [2 1 3]]
[[2 3 3]
 [4 6 6]
 [2 1 3]]
Определитель матрицы A: 0.0


### Обратная матрица

In [59]:
A = np.random.randint(1,5,(2,2))
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.16666667  0.33333333]
 [ 0.33333333 -0.16666667]]


#### Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [60]:
A = np.random.randint(1,5,(2,2))
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print("Определитель исходной матрицы:\n",A)
print("Определитель обратной обратной матрицы A:\n",A_inv_inv)

Определитель исходной матрицы:
 [[3 1]
 [4 3]]
Определитель обратной обратной матрицы A:
 [[3. 1.]
 [4. 3.]]


#### Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [61]:
A = np.random.randint(1,5,(2,2))
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print("Обратная матрица транспонированной матрицы:\n",L)
print("Транспонированная матрица от обратной матрицы:\n", R)

Обратная матрица транспонированной матрицы:
 [[ 0.5  -0.25]
 [-0.5   0.5 ]]
Транспонированная матрица от обратной матрицы:
 [[ 0.5  -0.25]
 [-0.5   0.5 ]]


#### Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [63]:
A = np.random.randint(1,5,(2,2))
B = np.random.randint(1,5,(2,2))
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print("Обратная матрица произведения матриц:\n",L)
print("Произведение обратных матриц:\n", R)

Обратная матрица произведения матриц:
 [[-0.42307692  0.36538462]
 [ 0.23076923 -0.15384615]]
Произведение обратных матриц:
 [[-0.42307692  0.36538462]
 [ 0.23076923 -0.15384615]]
