In [2]:
import numpy as np

### Вектор-строка

In [3]:
v_hor_zeros_v1 = np.zeros((5,))
print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0.]


In [4]:
 v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2)

[[0. 0. 0. 0. 0.]]


In [5]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)
                       
v_hor_one_v2 = np.ones((1, 5))
print(v_hor_one_v2)
                  

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]]


### Веткор-столбец

In [6]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [7]:
v_vert_zeros = np.zeros((5,1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [8]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


### Квадратная матрица

In [9]:
 m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Диагональная матрица

In [12]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)


[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [13]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
diag = np.diag(m_sqr_mx)
print(diag)
print('\n\n')
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[1 5 9]



[[1 0 0]
 [0 5 0]
 [0 0 9]]


### Единичная матрица

In [14]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
m_idnt = np.identity(3)
print(m_idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Нулевая матрица

In [17]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Транспонирование матрицы

In [18]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [19]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
B = np.matrix('1 2 3; 4 5 6')
print(B.T)

[[1 4]
 [2 5]
 [3 6]]


Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [21]:
A = np.matrix('1 2 3; 4 5 6')
print(A)
print((A.T).T)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [22]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A+B).T
R = A.T + B.T
print(L)
print(R)

[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке

In [23]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [24]:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * A.T
print(L)
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


*Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [25]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

-2
-2


### Действия над матрицами

#### Умножение матрицы на число

In [26]:
A = np.matrix('1 2; 3 4')
print(A * 3)

[[ 3  6]
 [ 9 12]]


Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице

Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел

Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [27]:
A = np.matrix('1 2; 3 4')
print(A * 1)

[[1 2]
 [3 4]]


In [28]:
A = np.matrix('1 2; 3 4')
print(A * 0)

[[0 0]
 [0 0]]


In [29]:
A = np.matrix('1 2; 3 4')
q = 2
p = 3
L = (q + p) * A
R = q * A + p * A
print(L)
print(R)

[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]


In [30]:
A = np.matrix('1 2; 3 4')
q = 2
p = 3
L = (q * p) * A
R = q * (p * A)
print(L)
print(R)

[[ 6 12]
 [18 24]]
[[ 6 12]
 [18 24]]


In [31]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]


#### Сложение матрицы

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться

Свойство 3. Для любой матрицы существует противоположная ей, такая, что их сумма является нулевой матрицей :

In [32]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)
print(R)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [33]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


In [34]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


#### Умножение матриц

In [35]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция

Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц

Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей

Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице

Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице

In [36]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [37]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[35 42]
 [77 94]]
[[35 42]
 [77 94]]


In [38]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A.dot(B)
R = B.dot(A)
print(L)
print(R)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [39]:
A = np.matrix('1 2; 3 4')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)
print(R)
print(A)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [40]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)
print(R)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


### Определитель матрицы

In [41]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [42]:
np.linalg.det(A)

-14.000000000000009

#### Свойства определителя матрицы.
Свойство 1. Определитель матрицы остается неизменным при ее транспонировании

Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определительтакой матрицы равен  нулю

Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный

Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю

Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число

Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц

Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится

Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю

Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю

In [43]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]
-14.0
-14.0


In [44]:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


0.0

In [45]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
print(round(np.linalg.det(A), 3))
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)
print(round(np.linalg.det(B), 3))

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
-14.0
[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]
14.0


In [46]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


0.0

In [47]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print(det_A * k)
print(det_B)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]
-28.0
-28.0


In [48]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
print(round(np.linalg.det(C), 3))
print(round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3))

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]
4.0
4.0


In [49]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
print(round(np.linalg.det(A), 3))
print(round(np.linalg.det(B), 3))

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]
-14.0
-14.0


In [50]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
print(A)
print(round(np.linalg.det(A), 3))

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [12  5  4]
 [ 8  3  1]]
0.0


In [51]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
print(round(np.linalg.det(A), 3))

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]
0.0


### Обратная матрица

In [52]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [53]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]
[[ 1. -3.]
 [ 2.  5.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [54]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]
[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [55]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


### Ранг матрицы

In [56]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4


In [58]:
m_eye[3][3] = 0
print(m_eye)
rank = np.linalg.matrix_rank(m_eye)
print(rank)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
3
